### ISSUE TITLE
No such file or directory on installing

### ISSUE THREAD

**Issue by dan1-ru** [singnet/snet-sdk-python#17]
Hello!

When I try to run command 
./scripts/blockchain install
I see this error:
![Screenshot from 2019-03-12 01-02-04](https://user-images.githubusercontent.com/7466036/54154419-af006300-4463-11e9-9cac-f51986f62696.png)

After creating an empty "contracts" directory at snet_sdk/resources, the installation was successful. I understand that the empty directory did not get into the repository, but can you add a command in readme?

**Comment by bulidiriba** [comment]
Hi @dan1-ru 

I also face this issue similarly, have you solve it ?

**Comment by bulidiriba** [comment]
oho I have just found solution for this issue in the Pull requests just adding two lines of code in the scripts/blockchain function
 https://github.com/singnet/snet-sdk-python/pull/18

**Comment by vforvalerio87** [comment]
Hey, this SDK is officially deprecated and the repository will soon be archived.

The new Python SDK is now in the snet-cli monorepo which features both the CLI and the Python SDK (https://github.com/singnet/snet-cli)

The PyPI package is called `snet.sdk` (https://pypi.org/project/snet.sdk/)
