### ISSUE TITLE
SDK/CLI separation: snet identity create

### ISSUE THREAD

**Issue by Necr0x0Der** [singnet/snet-sdk-python#32]
It's ok from SDK user perspective that CLI is installed together with SDK (although it can still be improved from the design perspective), but the necessity to run `snet` in command line is not good. In particular, to start using SDK, `snet identity create` is required.

How to reproduce:
* create a fresh environment (without .snet in the home directory)
* pip install snet.sdk
* run test_sdk_client.py

SDK should not require running CLI manually and should not depend on its config since `snet_sdk = sdk.SnetSDK(config)` accepts `config`, which can contain anything needed (rather CLI should rely on sdk.SnetSDK)

**Comment by PAY2109** [comment]
Dear Necr0x0Der,
Thank you for reporting this issue. We appreciate your feedback and apologize for any inconvenience caused. After thorough investigation, we have resolved this issue in the latest version of our app.
SDK now creates identity automatically.
Please update to the most recent release, and if you encounter any further problems, feel free to reopen this issue or create a new one.
Best regards, Paul, SingularityNET

**Comment by Necr0x0Der** [comment]
Now, it works without explicit `snet identity create`, which is good. However, it creates `config` with `identity.test`, default endpoints, session on sepolia network. They seem to be ignored, so this is more or less ok, but they save my private key in config, which is not nice.
