### ISSUE TITLE
Excessive fields in SnetSDK config: org_id, service_id

### ISSUE THREAD

**Issue by Necr0x0Der** [singnet/snet-sdk-python#34]
`sdk.SnetSDK(config)` raises the key absent error, when `org_id` and `service_id` are not provided. Downloadable integration files from the marketplace do not contain these fields in `config`, so these fields were mistakingly introduced during refactoring. They should not be needed since, say, `snet_sdk.create_service_client(org_id, service_id, group_name)` also accepts `org_id` and `service_id`, and we may want to use `SnetSDK` with multiple services belonging to multiple organizations.

**Comment by PAY2109** [comment]
Dear @Necr0x0Der,
Thank you for reporting this issue. We appreciate your feedback and apologize for any inconvenience caused. After thorough investigation, we have resolved this issue in the [v3.3.0](https://github.com/singnet/snet-sdk-python/releases/tag/v3.3.0) of our app.
create_service_client() method takes no arguments now. Please specify org_id and service_id in the config dictionary.
Please update to the most recent release, and if you encounter any further problems, feel free to reopen this issue or create a new one.
Best regards, Paul, SingularityNET
