### ISSUE TITLE
README.md : broken link

### ISSUE THREAD

**Issue by Necr0x0Der** [singnet/snet-sdk-python#35]
The link [test_sdk_client.py.sample](https://github.com/singnet/snet-cli/blob/master/packages/sdk/testcases/functional_tests/test_sdk_client.py) should be fixed

**Comment by PAY2109** [comment]
Dear Necr0x0Der,
Thank you for reporting this issue. We appreciate your feedback and apologize for any inconvenience caused. After thorough investigation, we have resolved this issue in the latest version of our app.
Please update to the most recent release, and if you encounter any further problems, feel free to reopen this issue or create a new one.
Best regards, Paul, SingularityNET

**Comment by Necr0x0Der** [comment]
The following link in the README.md is broken:
```
You can get this code example at https://github.com/singnet/snet-code-examples/tree/python_client/python/client
```
