### ISSUE TITLE
Excessive _pb2 files in functional_tests?

### ISSUE THREAD

**Issue by Necr0x0Der** [singnet/snet-sdk-python#36]
Execution of [test_sdk_client.py](https://github.com/singnet/snet-sdk-python/blob/master/testcases/functional_tests/test_sdk_client.py) produces `examples_service_pb2_grpc.py` and `examples_service_pb2.py` in the `.snet` subfolder. Are these files needed for testing, or should they be removed from the repo as confusing and excessive?

**Comment by PAY2109** [comment]
Dear Necr0x0Der,
Thank you for reporting this issue. We appreciate your feedback and apologize for any inconvenience caused. After thorough investigation, we have resolved this issue in the latest version of our app.
These files have been removed from the repository. Also the test_sdk_client.py script now removes the files that it creates in the .snet directory.
Please update to the most recent release, and if you encounter any further problems, feel free to reopen this issue or create a new one.
Best regards, Paul, SingularityNET
