### ISSUE TITLE
Optional protobuf compilation when it already exists

### ISSUE THREAD

**Issue by Necr0x0Der** [singnet/snet-sdk-python#39]
It seems that the service information is requested each time from the platform, and protobuf compilation is done each time.
Running the same script two times in a row produces the following messages each time:
```
~/.snet/naint/image-generation/python/Generation.proto removed.
client libraries for service with id "image-generation" in org with id "naint" generated at ~/.snet/naint/image-generation/python
```

This process requires several seconds. It should not be done each time. This can be achieved in different ways:
* if the necessary folder exists, the info is not requested and compilation is not done by default. The flag `force_update` (or with another name) can be introduced to redo this.
* Service versions can be supported, and only the version can be requested, and compilation can be redone if versions mismatch.
* Other criteria like time passed?

**Comment by PAY2109** [comment]
Dear Necr0x0Der,
Thank you for reporting this issue. We appreciate your feedback and apologize for any inconvenience caused. After thorough investigation, we have resolved this issue in the latest version of our app. 
The config now supports optional force_update key. If set to False (default) it will not re-download the proto file and re-generate the gRPC stubs if they already present in the .snet directory.
Please update to the most recent release, and if you encounter any further problems, feel free to reopen this issue or create a new one.
Best regards, Paul, SingularityNET

**Comment by Necr0x0Der** [comment]
Thanks. It seems to work. The only question is what is the parameter for forcing proto files to be reloaded and recompiled? I'm not sure if this parameter should be `True` or `False` by default, but we may need control over it in any case

**Comment by PAY2109** [comment]
@Necr0x0Der if force_update is set to True, the SDK will always reload and recompile the proto files
